language: node_js
node_js:
  - 12.18.1
cache: yarn

install:
  - yarn install

script:
  - CI=false yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main