dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - yarn install

script:
  - CI=false yarn run build

after_success:
  - yarn add -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"
