dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - CI=false npm run build

after_success:
  - npm install -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"
